#!/usr/bin/env python3
"""Generate src/reaper/native_actions.gen.h from tools/native_actions.tsv.

The TSV holds REAPER's native (built-in) action IDs and names — the actions
that REAPER does NOT expose through kbd_getTextFromCmd/kbd_enumerateActions and
therefore cannot be enumerated live at runtime. Bundling them lets the catalog
make native actions name-searchable. See tools/README.md for regeneration.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "native_actions.tsv")
OUT = os.path.normpath(os.path.join(HERE, "..", "src", "reaper", "native_actions.gen.h"))


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    entries = []
    with open(SRC, encoding="utf-8") as f:
        for line in f:
            if not line.strip() or line.startswith("#"):
                continue
            cid, name = line.rstrip("\n").split("\t", 1)
            entries.append((int(cid), name))
    entries.sort(key=lambda e: e[0])

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by tools/gen_native_actions.py — DO NOT EDIT.\n")
        f.write("// Source: tools/native_actions.tsv (REAPER native action ID -> name).\n")
        f.write("#pragma once\n\n")
        f.write("namespace ReaClaw::Catalog {\n\n")
        f.write("struct NativeAction {\n    int id;\n    const char* name;\n};\n\n")
        f.write("// REAPER's built-in actions are not enumerable via the SDK; this static\n")
        f.write("// table backs name-based discovery for them. Native command IDs are stable\n")
        f.write("// across REAPER versions and platforms.\n")
        f.write("inline constexpr NativeAction k_native_actions[] = {\n")
        for cid, name in entries:
            f.write(f'    {{{cid}, "{c_escape(name)}"}},\n')
        f.write("};\n\n")
        f.write(f"inline constexpr int k_native_actions_count = {len(entries)};\n\n")
        f.write("}  // namespace ReaClaw::Catalog\n")

    print(f"wrote {OUT}: {len(entries)} native actions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
