# Embed a file into a generated header as a byte array.
#   cmake -DIN=<file> -DOUT=<header> -DVAR=<symbol> -P embed_file.cmake
# Bytes, not a string literal — MSVC caps string literals at 64KB.
file(READ "${IN}" _hex HEX)
string(REGEX REPLACE "(..)" "0x\\1," _bytes "${_hex}")
file(WRITE "${OUT}"
     "// Generated by cmake/embed_file.cmake from ${IN} — do not edit.\n"
     "#pragma once\n"
     "static const unsigned char ${VAR}[] = {${_bytes}};\n"
     "static const unsigned int ${VAR}_len = sizeof(${VAR});\n")
